version: "3.9"

services:
  app:
    build: .
    image: search_analytics
    container_name: search_analytics_app
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"  # Optional if you're using env_file
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    command: ["./start.sh"]
    stdin_open: true
    tty: true

  db:
    image: postgres:17.0
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: search_analytics_production
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
