version: "3.9"

services:
  app:
    build: .
    image: search_analytics
    container_name: search_analytics_app
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    command: ["./start.sh"]
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgres:17.0
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: search_analytics_production
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sidekiq:
    build: .
    image: search_analytics
    container_name: search_analytics_sidekiq
    command: ["bundle", "exec", "sidekiq"]
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: "${RAILS_MASTER_KEY}"
      UPSTASH_REDIS_REST_URL: "${UPSTASH_REDIS_REST_URL}"
      UPSTASH_REDIS_REST_TOKEN: "${UPSTASH_REDIS_REST_TOKEN}"
    volumes:
      - .:/rails

volumes:
  postgres_data:
